on:
  push:
    branches: dev

name: trigger-aws

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - run: |
            python -c 'import os, json; print(json.dumps(os.listdir("../")))'
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: 'matrix-ci'
          client-payload:  '{"images": ${{steps.file_changes.outputs.files}} }'
