on:
  push:
    branches: dev
    # paths:
    #   - 'config/**.yaml'

name: trigger-aws

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - run: |
          array=(${{steps.file_changes.outputs.files}})
          newarray=( $(printf "%s\n" "${array[@]}" | grep ^elem/) )
          echo "::set-output name=configs::{${{steps.file_changes.outputs.files}}[@]/config}"
          echo "${{steps.file_changes.outputs.files}}"
          echo "${{steps.file_changes.outputs.files}}" | sed -e 's/config\///g'  | sed -e 's/.yaml//g'

      - name: test
        run: echo "${{steps.file_changes.outputs.configs}}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: 'matrix-ci'
          client-payload:  '{"images": ${{steps.file_changes.outputs.files}} }'
